Initial Structure
Piletskii-Oleg/chunkfs pull request #1
Opened 2024-03-11 10:44 UTC by Piletskii-Oleg

First working prototype of chunkfs library
Supports writing to and reading from a file, chunking it with Fixed Size Chunking.
Hashes are stored as Vec<u8>, the only hasher simply takes the input and clones it.
Can only open and operate on a single file at a time, otherwise storage gets broken because of inner buffer

2024-03-12 13:01 UTC, dsemak requested changes
- Для драфта в целом все ок. Нужно добавить комментариев в формате Rust doc для всех структур, полей структуры, трейтов и функций, чтобы было понятно что это и для чего.

- Также можно не выносить отдельные модули в storage, потому что chunker и hasher это не совсем сторадж. Сейчас кода мало и можно оставить все в src.

- Также некоторые функции используются только в тестах. Весь этот код делается как библиотека, поэтому нужно определить, что должно торчать наружу.

2024-03-12 13:01 UTC, dsemak commented on src/file_layer.rs
> +        if self.files.iter().find(|file| file.name == name).is_some() {
Лучше сделать HashMap с ключом по имени. Поиск по вектору будет долгий

2024-03-12 13:01 UTC, dsemak commented on src/file_layer.rs
> +pub enum FileError {
Не очень понял, зачем отдельный тип ошибок, если есть std::io::Error

2024-03-12 13:01 UTC, dsemak commented on src/file_layer.rs
> +    fn from_file(file: &File) -> Self {
Лучше сделать конструктором new, а не from_file

2024-03-12 13:01 UTC, dsemak commented on src/storage.rs
> +        assert_eq!(data.len(), SEG_SIZE); // we assume that all given data segments are 1MB long for now
лучше заменить на debug_assert

2024-03-12 13:01 UTC, dsemak commented on src/storage.rs
> +        let data = &self.buffer; // this, or replace all occurrences of data with self.buffer
Лучш заменить на &self.buffer

2024-03-12 13:01 UTC, dsemak commented on src/storage.rs
> +        self.buffer.extend_from_slice(data); // remove copying? we need to have `rest` stored and indexed
Сделай лучше аллокатор, который будет заранее выделять какое-то количество Mb и туда будут перемещаться данные. Как только буфер будет привышен, то будет происходить автоматический flush.

Сейчас будет много копирований и вектор будет сильно пухнуть в размере.

2024-03-12 13:01 UTC, dsemak commented on src/storage/base.rs
> +            .map(|hash| self.segment_map.get(&hash).unwrap().clone())
Лучше возвращать ошибку ErrorKind::NotFound, а то сейчас будет паника

2024-03-12 13:01 UTC, dsemak commented on src/file_layer.rs
> +pub struct FileHandle {
Не очень понял зачем он нужен

2024-03-12 13:01 UTC, dsemak commented on src/file_layer.rs
> +pub struct FileLayer {
Debug лушче убрать, плохая практика делать это для структур с векторами

2024-03-12 13:01 UTC, dsemak commented on src/file_layer.rs
> +pub struct File {
Аналогично, Debug лушче убрать

2024-03-12 13:01 UTC, dsemak commented on src/file_layer.rs
> +pub struct FileSpan {
А почему бы еще не добавить Eq и Default?

2024-03-12 13:01 UTC, dsemak commented on src/storage/base.rs
> +    fn retrieve(&mut self, request: Vec<Hash>) -> std::io::Result<Vec<Vec<u8>>>;
В файловой системе Hash параметризированный, тут надо делать также, так как это трейт и Hash может быть любым, главное чтобы он реализовывал наш трейт Hash.

2024-03-12 13:01 UTC, dsemak commented on src/file_layer.rs
> +    pub fn new() -> Self {
Не нужен такой new, для этого есть Default

2024-03-12 13:01 UTC, dsemak commented on src/file_layer.rs
> +        if self.files.iter().find(|file| file.name == name).is_some() {
```suggestion
        if self.files.iter().any(|file| file.name == name) {
```

2024-03-12 13:01 UTC, dsemak commented on src/file_layer.rs
> +        if let Some(file) = self.files.iter().find(|file| file.name == name) {
```suggestion
        self.files.iter().find(|file| file.name == name).map(|file| FileHandle::from_file(file))
```

2024-03-12 13:01 UTC, dsemak commented on src/storage.rs
> +        return Ok(span);
```suggestion
        Ok(span)
```

2024-03-12 13:01 UTC, dsemak commented on src/system.rs
> +        let hashes = self.file_layer.read(&handle);
```suggestion
        let hashes = self.file_layer.read(handle);
```

2024-04-22 10:06 UTC, IgorErin reviewed
Непонятные выражение, которые хочется сделать константами

2024-04-22 10:06 UTC, IgorErin commented on src/bin/write_read.rs
> +    const MB_COUNT: usize = 1024;
Дальше часто используется магическое число, равное этой константе. Так и должно быть?

2024-04-22 10:06 UTC, IgorErin commented on src/bin/write_read.rs
> +        fs.write_to_file(&mut file, &data[1024 * 1024 * i..1024 * 1024 * (i + 1)])?;
Тут, например. Да и вообще, выражение очень сложное, может его в функцию винести?

2024-04-22 10:06 UTC, IgorErin commented on src/chunker.rs
> +        data.len() / 1024 * 8
Опять

2024-04-22 10:06 UTC, IgorErin commented on src/bin/write_read.rs
> +    assert_eq!(read.len(), 1024 * 1024 * MB_COUNT);
Много раз 1024 * 1024. Может тоже в константу?

2024-04-22 10:06 UTC, IgorErin commented on tests/filesystem.rs
> +    let ones = vec![1; 1024 * 1024];
Опять оно, и оно везде, но непонятно что это...

2024-05-10 06:59 UTC, merged